# What do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce # This means the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi # (We need only 1 from the 2GB available)

---
# How do we want it to be implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-local-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi # This is the size of the persistent volume (All we have is 10GB)
  hostPath:
    path: "/mnt/some/directory/structure" # This is the path on the host machine where the data will be stored
    type: DirectoryOrCreate # This will create the directory if it does not exist

# As we can see, PersistentVolumeClaim does not reference any PersistentVolume.
# Next commit will show how to link them together.
