apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.5-jessie
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: "/data/db" #folder inside the container that will be mapped to the persistent volume on the host, outside the container
      volumes:
        - name: mongodb-persistent-storage
          hostPath:
            path: /host_mnt/c/test-mobgo-k8s-volume/db #path on the host machine where the data will be stored, outside the container
            type: DirectoryOrCreate #if the path does not exist, it will be created

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017

  type: ClusterIP
