# What do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: mylocalstorage # This is the name of the storage class we want to use
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# How do we want it to be implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-local-storage
spec:
  storageClassName: mylocalstorage # This is the name of the storage class we want to use
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/mnt/some/directory/structure"
    type: DirectoryOrCreate
