apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: position-tracker # This is the name of the container does not matter
          image: richardchesterwood/k8s-fleetman-position-tracker:release1

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080

  type: ClusterIP
