apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue

spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template: # the template for POD, would be beter if it would be called POD instead
    # in here we put the exact same settings as for individual pod
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: richardchesterwood/k8s-fleetman-queue:release2

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
    - name: http
      port: 8161

    - name: endpoint
      port: 61616

  type: ClusterIP
