apiVersion: v1
kind: Service
metadata:
  # 'name' is VERY important — other components will use it in the URL to reach this service
  name: fleetman-webapp

spec:
  # this defines which PODS are going to be represented by this service
  # the service becomes a network endpoint for either other services or maybe esternal users to connect to (eg. browser)
  selector:
    app: webapp # 'webapp' is the name of our pod
    release: "0-5"
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080 # only port numbers greater then 30000 are allowed. This property only for Service type - NodePort
  type: NodePort # this type is available from outside of a cluster (opposite to ClusterIP)
